name: mobile_labs
description: "Lab 3: Clean architecture with local auth in Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  mqtt_client:
  usb_serial:
  mobile_scanner:
  rxdart:

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/avatar.png
